const express=require('express')
const cors=require('cors')
const app=express()
const path=require('path')
const http=require('http')
const user=require('./router/user')
const bodyParser=require('body-parser')
const jwt=require('./_helpers/jwt')
const init_io=require('./socket/index')
const server=http.createServer(app)
const errorhander=require('./_helpers/error_hander')
app.use(cors())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.use('/imageSave',express.static(path.join(__dirname,'/image_save')))
// app.use(jwt())
init_io(server)
app.use('/user',user)
app.use(errorhander)
server.listen(5566,()=>{
    console.log('服务已启动，地址为：http://192.168.10.2:5566')
})